# Generated by Django 3.2.9 on 2021-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='state',
            field=models.CharField(choices=[('BUSY', 'busy'), ('FREE', 'free'), ('RESERVED', 'reserved')], default='BUSY', max_length=8),
        ),
    ]
