# Generated by Django 3.2.9 on 2021-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_layout', '0002_table_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
