# Generated by Django 3.2.9 on 2021-11-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables_layout', '0003_alter_table_id'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_order',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables_layout.table'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
