# Generated by Django 3.2.9 on 2021-11-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211121_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('GUEST', 'guest'), ('WAITER', 'waiter'), ('KITCHEN', 'kitchen'), ('BAR', 'bar'), ('MANAGER', 'manager')], default='GUEST', max_length=10),
        ),
    ]
