# Generated by Django 3.2.9 on 2021-11-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='course_name',
            new_name='dish_name',
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dishtype'),
        ),
    ]
